// TOEFL Vocabulary Export Manager
// Handles exporting filtered vocabulary to Anki CSV and Markdown formats

class VocabularyExport {
    constructor(dataManager) {
        this.data = dataManager;
    }

    exportToAnki() {
        const words = this.data.getSelectedWords();
        if (words.length === 0) {
            alert('No words selected. Please select words to export.');
            return;
        }

        const csv = this._generateAnkiCSV(words);
        this._downloadCSV(csv, 'toefl_vocabulary_anki.csv');
    }

    exportToMarkdown() {
        const words = this.data.getSelectedWords();
        if (words.length === 0) {
            alert('No words selected. Please select words to export.');
            return;
        }

        // Group by register for better organization
        const grouped = this._groupBy(words, 'register');

        let markdown = this._generateMarkdown(grouped);
        this._downloadFile(markdown, 'toefl_vocabulary.md', 'text/markdown');
    }

    _generateAnkiCSV(words) {
        // Anki CSV format: front, back, tags
        const rows = words.map(word => {
            const front = word.word;

            // Back includes all classification data
            const back = [
                `Lemma: ${word.lemma}`,
                `POS: ${word.pos}`,
                `Word Family: ${word.word_family.slice(0, 10).join(', ')}${word.word_family.length > 10 ? '...' : ''}`,
                `Frequency: ${word.frequency?.band || 'N/A'}`,
                `Emotion: ${word.emotion?.primary || 'neutral'}`,
                `Register: ${word.register?.register || 'general'}`,
            ].join('<br>');

            // Tags for filtering in Anki
            const tags = [
                `band-${word.frequency?.band || 'unknown'}`,
                word.emotion?.primary || 'neutral',
                word.register?.register || 'general',
                word.pos || 'unknown'
            ];

            // Escape quotes for CSV
            const escapeCSV = (str) => {
                if (str.includes('"') || str.includes(',')) {
                    return `"${str.replace(/"/g, '""')}"`;
                }
                return str;
            };

            return `"${escapeCSV(front)}","${escapeCSV(back)}","${escapeCSV(tags.join(' '))}"`;
        });

        // Add header
        return '#frontierte,back,tags\n' + rows.join('\n');
    }

    _generateMarkdown(grouped) {
        let markdown = '# TOEFL Vocabulary\n\n';
        markdown += '*Generated by TOEFL Vocabulary Classifier*\n\n';
        markdown += `*Total: ${Object.values(grouped).reduce((sum, g) => sum + g.length, 0)} words*\n\n---\n\n`;

        // Section for each register
        const registers = ['formal', 'neutral', 'informal', 'slang'];
        registers.forEach(register => {
            if (grouped[register]) {
                const words = grouped[register];
                markdown += `## ${register.charAt(0).toUpperCase() + register.slice(1)} (${words.length} words)\n\n`;

                words.forEach(word => {
                    markdown += `### ${word.word}\n`;
                    markdown += `- **Lemma**: ${word.lemma}\n`;
                    markdown += `- **POS**: ${word.pos}\n`;
                    markdown += `- **Frequency**: ${word.frequency?.band || 'N/A'}\n`;
                    markdown += `- **Emotion**: ${word.emotion?.primary || 'neutral'}\n`;
                    markdown += `- **Word Family**: ${word.word_family.join(', ')}\n`;
                    markdown += '\n';
                });

                markdown += '---\n\n';
            }
        });

        return markdown;
    }

    _groupBy(words, key) {
        return words.reduce((groups, word) => {
            const k = word[key] || 'unknown';
            if (!groups[k]) {
                groups[k] = [];
            }
            groups[k].push(word);
            return groups;
        }, {});
    }

    _downloadCSV(content, filename) {
        const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
        const url = URL.createObjectURL(blob);

        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.style.display = 'none';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    _downloadFile(content, filename, type = 'text/plain') {
        const blob = new Blob([content], { type });
        const url = URL.createObjectURL(blob);

        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.style.display = 'none';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    showExportStats() {
        const stats = this.data.getSelectionStats();
        const total = stats.total;
        const selected = stats.selected;

        if (total === 0) {
            alert('No words to export.');
            return;
        }

        const message = selected > 0
            ? `Export ${selected} words (${stats.percentage}%) to Anki/Markdown?`
            : `Export all ${total} words to Anki/Markdown?`;

        if (confirm(message)) {
            this.exportToAnki();
        }
    }
}

// Export functionality
document.addEventListener('DOMContentLoaded', () => {
    const exportAnkiBtn = document.getElementById('exportAnkiBtn');
    const exportMarkdownBtn = document.getElementById('exportMarkdownBtn');

    if (exportAnkiBtn) {
        exportAnkiBtn.addEventListener('click', () => {
            if (typeof vocabularyExport !== 'undefined') {
                vocabularyExport.exportToAnki();
            }
        });
    }

    if (exportMarkdownBtn) {
        exportMarkdownBtn.addEventListener('click', () => {
            if (typeof vocabularyExport !== 'undefined') {
                vocabularyExport.exportToMarkdown();
            }
        });
    }
});
